# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 'Build de Artefato de API em .Net Core'

trigger:
  branches: 
    include: 
      - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release' 
  nugetVersion: '6.11.0'  # Use uma versão específica do NuGet aqui

jobs:
  - job: BuildTestProd
    displayName: 'Teste de Produção em Artefato'
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '$(nugetVersion)'  # Use a variável para a versão

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'agroconnect'
        publishLocation: 'Container'